### ISSUE TITLE
Jan is not listed in the dropdown of dates

### ISSUE THREAD

**Issue by felskia** [map-yemen/admin#6]
Might just be importing things from Map Egypt to fix this but we need to fix it here.

Hagar's comment: 
In the dropdown menu for the start and end dates of projects, January is not listed with the other months (this was the case for MAP Egypt too before, now it is fixed for Egypt but still not for Yemen – we suggest revising MAP Yemen similarly, after solving the Egypt issues, to make sure both have no bugs)

**Comment by kamicut** [comment]
This is fixed by bringing map-yemen 1:1 with map-egypt
