### ISSUE TITLE
422 Unprocessable entity 

### ISSUE THREAD

**Issue by felskia** [map-yemen/admin#8]
Form doesn't submit with certain inputs:

Fields that were filled out: 
- Project Name
- Objective
- Visibility: Draft
- Component
- Status: Ongoing
- Month and Year for:
     - Contract Signed
     - Planned Start Date
     - Actual Start Date
     - Planned End Date
- Number of beneficiaries: 3000 (number), houses (unit)
- SDG Goal: Goal 6
- Sub-sectors: Water
- Locations: Mareb, Sirwah
- Budget: US (currency), 3000 (amount), 1 (exchange rate)
    - Donor: USAID
    - Type: Loan

Tried to press submit and got errors to fill out KPI. Filled out KPI and pressed submit, got an error to fill out component in KPI so did that and the rest of required fields within KPI.

Pressed submit and got an error in the console: 
`422 Unprocessable Entity`

**Comment by kamicut** [comment]
I think this was an issue with the name field. We fixed this.
